### PR TITLE
Wbc result service navigation bug [#179779055]

### PR DESCRIPTION
**Pull request by olzraiti**
Bug description in: https://www.pivotaltracker.com/story/show/179779055
Demo: https://179779055.dev.laji.fi/project/MHL.3/stats?tab=species

### CODE REVIEW

**Comment by olzraiti** [comment]
Oops, forgot to wait for approval for this one. Converted to a draft.

**Comment by olzraiti** [comment]
Oh, I'm the task owner so I'll be the judge, jury, and executioner, muhahaha... Ready for review

**Review by aorin — CHANGES_REQUESTED** [review]
If you select a bird association area and then click a species, then the back button doesn't work. I think the `skipLocationChange: true` parameter should be somewhere on the `wbc-result-filters.component` since it adds the year query parameter

**Comment by olzraiti** [comment]
Fixed that

**Review by aorin — APPROVED** [review]
Looks good

**Pull request merged**
