### PR TITLE
Laji UI style refactor #168777440 #173303972

### PR DESCRIPTION
**Pull request by Blodir**
* all laji-ui css components are now written inside sass mixins and can be imported either by `@including` or importing matching root style file
* laji-ui internal css imports are altered such that you can `@import("vars")`, then redefine vars, then import the rest of the components that you wish, enabling easy customization of variables
* all laji-ui variables that are used internally within a scss file now use the !default keyword, and can be customized by defining the variable before importing the file
* some styles were slightly altered
* laji-information is now laji-page
* laji-page styles have been altered slightly to be more generic
* laji-page now has table styles
* I made the mistake (again) of basing this off the taxon-identification branch, so that has to be merged first
* probably should've split this into multiple commits but oh well

### CODE REVIEW

**Comment by vixriihi** [comment]
Could you run  `npm ci` and then run this (this is giving me a lot of warning in the console)

**Comment by Blodir** [comment]
> Could you run `npm ci` and then run this (this is giving me a lot of warning in the console)

@vixriihi Running dev server: `npm ci`, `npm start`, works without any issues on my system. Haven't tested builds with different configurations yet as they take 10+mins to build. Can you elaborate on how to reprod the issues?

**Comment by vixriihi** [comment]
For me running `npm start` gives tons of errors like these:
```
   ╷
76 │ $danger-7: hsl(0, 80, 30);
   │            ^^^^^^^^^^^^^^
   ╵
    projects\laji-ui\src\lib\_vars.scss 76:12  @import
    projects\laji\src\styles\laji.scss 8:9     root stylesheet

DEPRECATION WARNING: $lightness: Passing a number without unit % (30) is deprecated.

To preserve current behavior: $lightness * 1%

   ╷
76 │ $danger-7: hsl(0, 80, 30);
   │            ^^^^^^^^^^^^^^
   ╵
    projects\laji-ui\src\lib\_vars.scss 76:12  @import
    projects\laji\src\styles\laji.scss 8:9     root stylesheet

DEPRECATION WARNING: $saturation: Passing a number without unit % (90) is deprecated.

To preserve current behavior: $saturation * 1%

   ╷
77 │ $danger-8: hsl(0, 90, 20);
   │            ^^^^^^^^^^^^^^
   ╵
    projects\laji-ui\src\lib\_vars.scss 77:12  @import
    projects\laji\src\styles\laji.scss 8:9     root stylesheet

DEPRECATION WARNING: $lightness: Passing a number without unit % (20) is deprecated.

To preserve current behavior: $lightness * 1%

   ╷
77 │ $danger-8: hsl(0, 90, 20);
   │            ^^^^^^^^^^^^^^
   ╵
    projects\laji-ui\src\lib\_vars.scss 77:12  @import
    projects\laji\src\styles\laji.scss 8:9     root stylesheet

DEPRECATION WARNING: $saturation: Passing a number without unit % (100) is deprecated.

To preserve current behavior: $saturation * 1%

   ╷
78 │ $danger-9: hsl(0, 100, 10);
   │            ^^^^^^^^^^^^^^^
   ╵
    projects\laji-ui\src\lib\_vars.scss 78:12  @import
    projects\laji\src\styles\laji.scss 8:9     root stylesheet

DEPRECATION WARNING: $lightness: Passing a number without unit % (10) is deprecated.

To preserve current behavior: $lightness * 1%

**Comment by Blodir** [comment]
PR now complies with the sass changes.

**Comment by vixriihi** [comment]
updated this branch so now diff is clear :) This looks good to me now, but since task referred here are not yet approved merging will have to wait

**Review by vixriihi — APPROVED** [review]

**Pull request merged**
