### PR TITLE
Don't populate leg into empty document when using named place [#178540041]

### PR DESCRIPTION
**Pull request by olzraiti**
Affects both prepopulated & accepted document.

Steps to reproduce:
1. Goto https://beta.laji.fi/project/MHL.1/form/MHL.1/places?activeNP=MNP.27408
2. Reserve the place to yourself
3. Compare https://beta.laji.fi/project/MHL.1/form/MHL.1/places/MNP.27408 and https://178540041.dev.laji.fi/project/MHL.1/form/MHL.1/places/MNP.27408 (beta shows Ville-Matti Riihikoski and you as observer, task demo site doesn't).

### CODE REVIEW

**Comment by aorin** [comment]
The new code doesn't take into account this option `form.options?.namedPlaceOptions?.includeUnits`. Is it not in use?

**Comment by olzraiti** [comment]
Good catch, I'll fix that

**Comment by olzraiti** [comment]
Fix'd

**Review by aorin — APPROVED** [review]
:+1:

**Pull request merged**
