### PR TITLE
Bird atlas result service updates

### PR DESCRIPTION
**Pull request by Blodir**
https://www.pivotaltracker.com/story/show/186060543
https://www.pivotaltracker.com/story/show/186060562
https://www.pivotaltracker.com/story/show/184243796
https://tuloksia-dev.lintuatlas.fi/

### CODE REVIEW

**Review by rpulkka — APPROVED** [review]
Good! Tested and reviewed.

**Comment by rpulkka** [comment]
I suppose this task was not included:
https://www.pivotaltracker.com/n/projects/2346653/stories/186060562
There's a full screen map viewer, but apparently it is impossible/difficult to download it as described in Pivotal. Not sure what that task's status should be now.

**Comment by rpulkka** [comment]
Optional improvement idea: Now .csv names are random, they could have a meaningful prefix like:
"selvitysasteet-<random>.csv"

**Comment by Blodir** [comment]
> I suppose this task was not included: https://www.pivotaltracker.com/n/projects/2346653/stories/186060562 There's a full screen map viewer, but apparently it is impossible/difficult to download it as described in Pivotal. Not sure what that task's status should be now.

We decided that just adding the option to full-screen laji-map was enough for this task

**Pull request merged**
