### PR TITLE
YKJ & EMK pages moved to CMS [#179505924]

### PR DESCRIPTION
**Pull request by olzraiti**
https://www.pivotaltracker.com/story/show/179505924
https://179505924.dev.laji.fi/theme

### CODE REVIEW

**Comment by MLumme** [comment]
@olzraiti Shouldn't bio-geographical province path to redirect in app-routing,modules.ts be theme/emk instead of theme/ekj? Otherwise looks fine.

**Comment by olzraiti** [comment]
Yes, nice catch :)

**Comment by MLumme** [comment]
Unfortunately still some issue, when trying to use https://179505924.dev.laji.fi/en/theme/emk the redirect doesn't trigger, it just shows Page Not Found, and while Swedish redirect works, the redirect removes /sv/ from the path and changes the entire site back to Finnish.

**Comment by olzraiti** [comment]
Thanks, fixed that.

**Comment by MLumme** [comment]
Still one more thing, which I did forget to check last time, sorry, the language reset is also present if redirect is done for /theme/ykj, present for both English and Swedish.

**Comment by olzraiti** [comment]
Hmm... https://laji.fi/sv/theme/ykj and https://laji.fi/en/theme/ykj aren't usable pages really, so I don't think we need to keep backward compatibility for those. Redirecting is done just for backward compatibility. To fix that, I'd have to add the routes to the root routing like emk, but I think we should keep hacks like that as minimal as possible if there's no real benefit.

**Comment by MLumme** [comment]
Aight, in that I'll mark this approved.

**Review by MLumme — APPROVED** [review]

**Pull request merged**
